spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            format_sql: true
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql: TRACE
